### PR TITLE
Fatts support

### PR DESCRIPTION
**Pull request by ftesser**
Hi Stéphane,

probably we (Giulio and me) have forget of this pull request.

If so I hope it is not too late.

Fabio.

### CODE REVIEW

**Comment by stephanemagnenat** [comment]
Hi Fabio,

I think that we should merge it into its own branch, not master.

**Comment by ftesser** [comment]
Ah, Ok, I am trying to do this.
But it seems that I am not able to merge in an non-existing branch
Perhaps you should to create the branch first?

**Comment by stephanemagnenat** [comment]
done, created branch fatts_support

**Comment by ftesser** [comment]
Ok I will do in another pull request. I close this one.

**Pull request closed without merging**
